### ISSUE TITLE
Error with end time

### ISSUE THREAD

**Issue by JesusGerardoAguiar** [lizashkod/react-timeline-range-slider#12]
Hi!, is it possible that the endTime only works after 12pm? Currently Im trying to set an interval between 9 am to 12 pm, and its not letting me, its giving an weird error "n is not a function", i also i noticed that the same happens if i use post 12 hours in startTime, i don't know if is this an issue or im using it wrong, thanks!

**Comment by JesusGerardoAguiar** [comment]
Hi, I managed to make it work!, now im struggling making the interval selected only one hour, the interval selected cannot be two hours long o three, only one sooo if someone knows how to achieve this let me know :), thanks!

**Comment by lizashkod** [comment]
Hi! Please, provide a demo, for example on [codesandbox](https://codesandbox.io/))

**Comment by JesusGerardoAguiar** [comment]
Hi! never mind, i managed to fix it and now is working properly, thanks for the response :)
