### ISSUE TITLE
Mulitple sliders depends

### ISSUE THREAD

**Issue by lokomass** [lizashkod/react-timeline-range-slider#15]
Hi,

Amazing plugin !
I'm trying to set 2 sliders. Slider 1 is forbidden interval for slider 2, and reverse.
When I update slider 1, disabledIntervals of slider 2 is updated, it's work great.
But when I update slider 1, onUpdateCallback of slider 2 is not triggered.
I want slider 1 error, call slider 2error function to check intervals.
Here is my working code :

https://codesandbox.io/s/react-timeline-range-slider-forked-9s26y?file=/src/App.js

Thanks for support

**Comment by lizashkod** [comment]
Hi! Thanks for the demo you provided.

If I understand your question correctly, then the slider behavior is correct. onUpdateCallback for slider 2 will be called only if the slider's 2 active area changes.

**Comment by lokomass** [comment]
Yes that's it.
I want onUpdateCallback fired on slider 2, if disabledIntervals of it changed.

**Comment by lizashkod** [comment]
I think the better way to do this is to use useEffect with the disabledIntervals dependency

**Comment by lokomass** [comment]
I've tried this,
But I don't see how can I call onUpdateCallback of a slider.

**Comment by lizashkod** [comment]
Just call setErrorPm(true) manually

**Comment by lizashkod** [comment]
I think this is the only way

**Comment by lokomass** [comment]
I don't know value of error : true or false.
I don't know when I change value of slider 1, if slider 2 will have to fire an error.
For example : 

Start of app with default values  : 
![image](https://user-images.githubusercontent.com/7886368/115216414-c3b08a00-a104-11eb-9e16-9eb845f03482.png)

Then, I change AM start date from 9 to 7:30 AM => no error on slider 2 so it's ok : set error false
![image](https://user-images.githubusercontent.com/7886368/115216538-e2168580-a104-11eb-8688-dff364f0e3d0.png)

But, now, if I set end of first slider after 2PM, we have to call onUpdateCallback on slider 2 and set error to true
![image](https://user-images.githubusercontent.com/7886368/115216735-138f5100-a105-11eb-9294-bcb73bd909da.png)

**Comment by lizashkod** [comment]
You need to check yourself is slider 2 is on error or not:
```
useEffect(() => {
  if (...) { // if am interval intersects pm interval
    setErrorPm(true)
  }
}, [am])
```
I’m afraid this can only be done manually, since the onUpdateCallback is called only after changing the slider value.

**Comment by lokomass** [comment]
Yesss, it's works with momenJS-range library : 

```
useEffect(() => {
    const range_am = moment.range(moment(am[0]), moment(am[1]))
    const range_pm = moment.range(moment(pm[0]), moment(pm[1]))
    const range = range_am.intersect(range_pm)
    setErrorAm(range !== null)
    setErrorPm(range !== null)
  }, [am, pm])
```

Thanks you !
