### ISSUE TITLE
Make Timeframes Draggable

### ISSUE THREAD

**Issue by schmidtfx** [lizashkod/react-timeline-range-slider#2]
Hi, very cool project. Are you planning to have the timeframes draggable as well?

**Comment by lizashkod** [comment]
Hi! I don't really understand what you mean. Can you describe it in more detail?

**Comment by vanch3d** [comment]
I think @schmidtfx meant to be able to drag the whole range left or right, keeping both handles with the same interval. 
At least I would love to have that 4th interaction mode :-)
Cool project indeed

**Comment by lizashkod** [comment]
@vanch3d I think I get it! This is an interesting idea, so I will implement it in the near future.

**Comment by subodhk01** [comment]
Yeah that would be a great feature to have

**Comment by schmidtfx** [comment]
What would be the best way to implement it? Maybe if you click on the timeframe, you will be able to move it. 
The problem is, that currently if you click on the timeframe one of the sides snaps to that location.

**Comment by lizashkod** [comment]
@schmidtfx How about making the edges movable? You hover the cursor over the edge of the timeline, then click and drag?
