### ISSUE TITLE
Return the time onUpdateCallback

### ISSUE THREAD

**Issue by gingerizer** [lizashkod/react-timeline-range-slider#6]
Currently only the error state is returned when the onUpdateCallback is fired.   It would also be extremely useful to have the current time, similar to the onChangeCallback.  That way components can react to change in time when the slider is dragged and not just when the dragging stops.

https://github.com/lizashkod/react-timeline-range-slider/blob/master/src/index.js#L96
Perhaps add: 
```
 const formattedNewTime = newTime.map(t => new Date(t))
 onUpdateCallback({ error: isValuesNotValid, time: formattedNewTime })
```

**Comment by lizashkod** [comment]
Hi! Thanks, added that on version 1.1.3.
